Numpy Basics

In [36]:
import numpy as np
import pandas as pd

In [3]:
# 1. Create a 1-dimensional NumPy array from a list of integers [1, 2, 3, 4, 5]. 
arr1 = np.array([1, 2, 3, 4, 5])
print("1D Array:", arr1)

1D Array: [1 2 3 4 5]


In [4]:
# 2. Create a 2-dimensional array of shape (3, 4) using np.array() with nested lists. 
arr2 = np.array([[1, 2, 3, 4],
                 [5, 6, 7, 8],
                 [9, 10, 11, 12]])
print("\n2D Array:\n", arr2)


2D Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [5]:
# 3. Use ndim, shape, size, and dtype to inspect the structure of an array. 
print("\nndim:", arr2.ndim)
print("shape:", arr2.shape)
print("size:", arr2.size)
print("dtype:", arr2.dtype)


ndim: 2
shape: (3, 4)
size: 12
dtype: int32


Array Creation and Initialization

In [6]:
# 1. Create a NumPy array with values from 10 to 50 using np.arange(). 
arr_range = np.arange(10, 51)
print("\nnp.arange 10–50:", arr_range)


np.arange 10–50: [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


In [7]:
# 2. Create an array of 10 equally spaced values between 1 and 100 using np.linspace().
arr_linspace = np.linspace(1, 100, 10)
print("\n10 equally spaced values:", arr_linspace)


10 equally spaced values: [  1.  12.  23.  34.  45.  56.  67.  78.  89. 100.]


In [8]:
# 3. Generate a 4x4 array of random integers between 1 and 100 using np.random.randint(). 
arr_randint = np.random.randint(1, 101, size=(4, 4))
print("\nRandom integers 4x4:\n", arr_randint)


Random integers 4x4:
 [[67  5 26 49]
 [69  3 77 37]
 [ 6 24 63  4]
 [98 31 36 89]]


In [9]:
# 4. Create a 3x3 matrix with normally distributed random numbers using np.random.randn().
arr_randn = np.random.randn(3, 3)
print("\nRandom normal 3x3:\n", arr_randn)


Random normal 3x3:
 [[ 0.25327903 -0.9876968   0.12415134]
 [ 1.40126706 -0.67876651 -0.53360425]
 [-1.41148695 -0.09526498  0.27711349]]


Array Reshaping and Manipulation

In [10]:
# 1. Reshape a 1D array of 12 elements into a 3x4 2D array.
arr12 = np.arange(1, 13).reshape(3, 4)
print("\nReshaped 3x4:\n", arr12)


Reshaped 3x4:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [11]:
# 2. Flatten a 2D array into a 1D array using .flatten() and .ravel().
print("\nFlatten:", arr12.flatten())
print("Ravel:", arr12.ravel())


Flatten: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Ravel: [ 1  2  3  4  5  6  7  8  9 10 11 12]


In [12]:
# 3. Concatenate two arrays horizontally and vertically using np.concatenate() or np.hstack()/np.vstack(). 
a1 = np.array([[1, 2], [3, 4]])
a2 = np.array([[5, 6], [7, 8]])
print("\nHorizontal concat:\n", np.hstack((a1, a2)))
print("Vertical concat:\n", np.vstack((a1, a2)))


Horizontal concat:
 [[1 2 5 6]
 [3 4 7 8]]
Vertical concat:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [13]:
# 4. Transpose a 2D array and observe how rows become columns.
print("\nTranspose:\n", arr12.T)


Transpose:
 [[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


Indexing, Slicing and Iteration

In [14]:
# 1. Access the element at the 2nd row and 3rd column of a 2D array. 
print("\nElement at (2nd row, 3rd col):", arr12[1, 2])


Element at (2nd row, 3rd col): 7


In [15]:
# 2. Slice a 1D array to get elements from index 2 to 6.
arr3 = np.arange(10)
print("Slice index 2 to 6:", arr3[2:7])


Slice index 2 to 6: [2 3 4 5 6]


In [19]:
# 3. Select all even numbers from a NumPy array using boolean indexing. 
even_nums = arr3[arr3 % 2 == 0]
print("Even numbers:", even_nums)

Even numbers: [0 2 4 6 8]


In [18]:
# 4. Replace all values in an array greater than 50 with 50. 
arr_replace = np.array([10, 55, 23, 77])
arr_replace[arr_replace > 50] = 50
print("Replace >50 with 50:", arr_replace)

Replace >50 with 50: [10 50 23 50]


Mathematical and Statistical Operations

In [20]:
# 1. Perform element-wise addition, subtraction, multiplication, and division between two arrays.
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
print("\nAdd:", x + y)
print("Subtract:", x - y)
print("Multiply:", x * y)
print("Divide:", x / y)



Add: [5 7 9]
Subtract: [-3 -3 -3]
Multiply: [ 4 10 18]
Divide: [0.25 0.4  0.5 ]


In [21]:
# 2. Use np.dot() or @ operator to perform matrix multiplication.
mat1 = np.array([[1, 2], [3, 4]])
mat2 = np.array([[5, 6], [7, 8]])
print("\nMatrix multiplication:\n", np.dot(mat1, mat2))


Matrix multiplication:
 [[19 22]
 [43 50]]


In [22]:
# 3. Calculate the mean, median, standard deviation, and variance of a NumPy array. 
stats_arr = np.array([10, 20, 30, 40])
print("Mean:", np.mean(stats_arr))
print("Median:", np.median(stats_arr))
print("Std Dev:", np.std(stats_arr))
print("Variance:", np.var(stats_arr))


Mean: 25.0
Median: 25.0
Std Dev: 11.180339887498949
Variance: 125.0


In [23]:
# 4. Compute the sum and product of all elements in a 2D array. 
print("Sum:", np.sum(arr12))
print("Product:", np.prod(arr12))

Sum: 78
Product: 479001600


In [24]:
# 5. Use np.cumsum() and np.cumprod() to find cumulative sum and product. 
print("Cumulative Sum:", np.cumsum([1, 2, 3]))
print("Cumulative Product:", np.cumprod([1, 2, 3]))

Cumulative Sum: [1 3 6]
Cumulative Product: [1 2 6]


In [25]:
# 6. Apply np.where() to create a new array where values > 10 are marked as 1, else 0. 
arr_where = np.array([5, 15, 8, 22])
new_arr = np.where(arr_where > 10, 1, 0)
print("np.where >10 → 1 else 0:", new_arr)

np.where >10 → 1 else 0: [0 1 0 1]


Data Type and Conversion

In [26]:
# 1. Check the dtype of an array and convert it to float using .astype(). 
print("\nDtype before:", arr1.dtype)
arr_float = arr1.astype(float)
print("Dtype after:", arr_float.dtype)


Dtype before: int32
Dtype after: float64


In [27]:
# 2. Create an array of strings and convert it to uppercase using np.char.upper(). 
str_arr = np.array(["apple", "banana", "cherry"])
print("Uppercase:", np.char.upper(str_arr))


Uppercase: ['APPLE' 'BANANA' 'CHERRY']


In [28]:
# 3. Use np.isnumeric() or np.isnan() to identify non-numeric or NaN values in an array. 
nan_arr = np.array([1, np.nan, 3])
print("Is NaN:", np.isnan(nan_arr))


Is NaN: [False  True False]


In [29]:
# 4. Convert a list of dates (as strings) into NumPy datetime64 objects. 
dates = np.array(["2021-01-01", "2022-05-15"], dtype='datetime64[D]')
print("Datetime64 array:", dates)

Datetime64 array: ['2021-01-01' '2022-05-15']


Advanced Indexing and Masking

In [30]:
# 1. Use a condition mask to extract all negative values from an array. 
arr_mask = np.array([-5, 2, -3, 7])
print("\nNegative values:", arr_mask[arr_mask < 0])


Negative values: [-5 -3]


In [31]:
# 2. Replace all values less than a threshold (e.g., 30) with 0. 
arr_thresh = np.array([10, 25, 40, 15])
arr_thresh[arr_thresh < 30] = 0
print("Replace <30 with 0:", arr_thresh)


Replace <30 with 0: [ 0  0 40  0]


In [32]:
# 3. Find the indices of all values greater than a threshold using np.where(). 
arr_idx = np.array([5, 15, 25, 35, 45])
indices = np.where(arr_idx > 20)
print("Indices where >20:", indices[0])

Indices where >20: [2 3 4]


In [33]:
# 4. Use np.take() to extract specific elements using a list of indices. 
taken = np.take(arr_idx, [0, 2, 4])
print("np.take specific indices:", taken)

np.take specific indices: [ 5 25 45]


In [34]:
# 4. Use np.unique() to extract unique elements and their counts from an array. 
unique_vals, counts = np.unique([1, 2, 2, 3, 3, 3], return_counts=True)
print("Unique values:", unique_vals)
print("Counts:", counts)

Unique values: [1 2 3]
Counts: [1 2 3]


Integration with Pandas(Bridge Concepts)

In [37]:
# 1. Convert a NumPy array into a Pandas DataFrame and assign column names. 
arr_for_df = np.array([[1, 2], [3, 4], [5, 6]])
df_from_arr = pd.DataFrame(arr_for_df, columns=["Col1", "Col2"])
print("\nDataFrame from array:\n", df_from_arr)


DataFrame from array:
    Col1  Col2
0     1     2
1     3     4
2     5     6


In [38]:
# 2. Create a DataFrame from a 2D NumPy array and perform .mean(), .sum(), etc., on it. 
print("Mean of DF:\n", df_from_arr.mean())
print("Sum of DF:\n", df_from_arr.sum())

Mean of DF:
 Col1    3.0
Col2    4.0
dtype: float64
Sum of DF:
 Col1     9
Col2    12
dtype: int64


In [39]:
# 3. Use .values to extract a NumPy array from a DataFrame. 
extracted_array = df_from_arr.values
print("Extracted NumPy array:\n", extracted_array)

Extracted NumPy array:
 [[1 2]
 [3 4]
 [5 6]]
